fix(ui): notifications appearing on top in unintended situations
AstroNvim/AstroNvim pull request #2093
Opened 2023-07-05 23:47 UTC by Subjective

This fixes an issue where notifications were obscuring UI elements of plugins like [Noice](https://github.com/folke/noice.nvim/blob/main/lua/noice/config/views.lua
).

2023-07-05 23:49 UTC, mehalter commented
What UI situations would happen in which you would not want the notification to appear on the top? I am not sure I can think of one

2023-07-05 23:51 UTC, mehalter commented
A screenshot might be helpful as well showing the unintended behavior

2023-07-06 00:05 UTC, Subjective commented
@mehalter The Noice cmdline. From what I can tell, setting the zindex 150 is low enough that it notifications appear above the cmdline while remaining underneath mason and lazy.
Before:
<img width="1787" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/e5ec9cdf-6867-426e-867b-8fadca18b4e5">
After:
<img width="1784" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/f3def3d9-2136-494f-9210-7664b088d388">

2023-07-06 00:42 UTC, mehalter commented
@Subjective if you set it to `200` will it show the last one on top? If a notification comes up while the command line is open then that would be over, but if you open the command line with a notification open then it would be on top? I'm not sure how ties are resolved. But I think that might be better behavior out of the box if possible

2023-07-06 00:49 UTC, mehalter requested changes

2023-07-06 00:49 UTC, mehalter commented on lua/plugins/ui.lua
> +        vim.api.nvim_win_set_config(win, { zindex = 150 })
```suggestion
        vim.api.nvim_win_set_config(win, { zindex = 175 })
```

Ok, after some testing and playing around, I think 175 is a good default here. I checked the zindex of our default plugins and this seems to be a good default. If other people want different results then they should override this themselves.

2023-07-06 01:43 UTC, mehalter approved these changes
Awesome! Thanks for taking the time to open a PR to resolve this :)

2023-07-06 01:43 UTC, merged