fix(provider): invalid buffer id in terminal buffer
AstroNvim/AstroNvim pull request #2280
Opened 2023-09-09 13:41 UTC by Subjective

## 📑 Description

Silences errors when exiting vertical/horizontal split terminal opened manually (e.g. `:horizontal terminal`)

## ℹ Additional Information
![Screen Recording 2023-09-09 at 6 36 42 AM](https://github.com/AstroNvim/AstroNvim/assets/56745535/f964e7f0-8d11-4802-a377-a0b3c6267f93)

2023-09-09 13:44 UTC, Subjective commented
Perhaps this isn't this best way to solve this, I still get an error message when exiting neovim:
<img width="1127" alt="image" src="https://github.com/AstroNvim/AstroNvim/assets/56745535/1a2f9641-1e8a-45ba-bd4d-96458cf08b10">

2023-09-09 13:44 UTC, mehalter requested changes
This shouldn't be done in the `buf_name` function but rather when it is used. `buf_name` is a parameter/argument potentially provided by the user. Could you please refactor this solution or I can do it sometime next week.

2023-09-09 13:45 UTC, mehalter commented
This this is not the ideal solution as this doesn't fix the problem you are running into. I would prefer we leave these errors actually so that we don't mask the real issue which would be the buffer management

2023-09-09 13:46 UTC, closed without merging

2023-09-09 13:49 UTC, mehalter commented
ohhhhhhh this is a bug only in neovim nightly @Subjective this has to do with a change in behavior that is probably considered a bug in neovim and not actually a bug in AstroNvim

2023-09-09 13:51 UTC, mehalter commented
From `:h news`:

```
• Terminal buffers started with no arguments (and use 'shell') close
  automatically if the job exited without error, eliminating the (often
  unwanted) "[Process exited 0]" message.
```

The automatic closing doesn't seem to be triggering our buffer management auto commands. I'll have to see if that's a neovim error or if there is some other auto command event we need to be listening to.

But if you just go to normal mode `<C-\><C-n>` and then run `:q` then it works completely normally

2023-09-09 13:52 UTC, mehalter commented
also `:horizontal`/`:vertical` is completely optional in this. You can replicate the same issue with just `:terminal`. Just to help guide this issue and fine tune what's really going on.

2023-09-09 13:55 UTC, Subjective commented
Weirdly enough, this only happens for me with `:horizontal` and `:vertical`

2023-09-09 13:56 UTC, mehalter commented
I can replicate without

2023-09-09 13:56 UTC, Subjective commented
nvm, it also happens without those, just not for a "[No Name]" buffer when opening neovim w/o arguments

2023-09-09 13:56 UTC, mehalter commented
@Subjective this is resolved on `nightly`

2023-09-09 13:57 UTC, Subjective commented
wow that was quick lol

2023-09-10 01:03 UTC, Subjective commented
Might be somewhat related, I get a the same error when closing out of the last window containing a "real" buffer when there is a quickfix window open elsewhere.

![Screen Recording 2023-09-09 at 5 57 27 PM](https://github.com/AstroNvim/AstroNvim/assets/56745535/0e84ba45-3cc5-46e3-9129-6a2c7f24f5ba)