Astronvim
AstroNvim/AstroNvim pull request #307
Opened 2022-04-17 19:32 UTC by kraxli

enhance #300 by providing (optional) terminal number

e.g. key stroke 4tp with open python in terminal  number 4

2022-04-17 19:35 UTC, mehalter commented
Thanks for the contribution! @kraxli  could you please rebase your commits into a single commit. We are not allowing any merge commits in main to keep a linear commit log.

2022-04-17 20:51 UTC, mehalter requested changes
Looks pretty great! I suggested one line change and other than that I just need you to rebase the commits back down to a single commit instead of having merge and revert commits.

2022-04-17 20:51 UTC, mehalter commented on lua/core/utils.lua
> +    term_key = term_details.cmd .. vim.v.count
Let's replace this line with `term_key = term_key .. vim.v.count`

2022-04-18 12:01 UTC, mehalter requested changes
Thanks for rebasing, its quite close. Can you please drop the unrelated commit that changes bufferline autocommands. Seems to be a problem with the Rebase.

2022-04-18 12:05 UTC, kraxli commented
thanks, I followed your  suggestion. Hope it fits now :-)

2022-04-18 12:21 UTC, mehalter approved these changes
LGTM

2022-04-18 12:21 UTC, merged