Update ascii art
AstroNvim/AstroNvim pull request #777
Opened 2022-07-22 03:00 UTC by osamuaoki

I have created 2 candidate for the higher resolution opening logo.
Use of Braille fonts should be OK since AstroNvim already require NerdFont.

Please check both logos.  Please pick one and remove others.

Adding removed logo in user_examples may be good idea.

2022-07-25 13:46 UTC, mehalter requested changes
Thanks so much for this contribution @osamuaoki ! These look great! I left a comment on the one I prefer and pinged @kabinspace to comment as well.

2022-07-25 13:46 UTC, mehalter commented on lua/configs/alpha.lua
> +        -- "⣰⣿⡿⠉⠉⠉⢹⣿⣿⢠⣶⣶⣶⣿⠟⠀⠸⣿⣿⣶⠀⣼⣿⡇⠀⠀⠀⢿⣿⣷⣶⣿⠟⠁⢰⣿⡟⠀⠀⠸⣿⣿⡿⠀⠀⠸⣿⣿⡟⠀⠀⣸⣿⡟⠀⣾⣿⡇⠀⣾⣿⡇⠀⣼⣿⡇",
I think I like this one the best, could you update the commit to use this one and remove the last one. @kabinspace what do you think of this updated ASCII art?

2022-07-26 16:55 UTC, mehalter commented on lua/configs/alpha.lua
> +        -- "⣰⣿⡿⠉⠉⠉⢹⣿⣿⢠⣶⣶⣶⣿⠟⠀⠸⣿⣿⣶⠀⣼⣿⡇⠀⠀⠀⢿⣿⣷⣶⣿⠟⠁⢰⣿⡟⠀⠀⠸⣿⣿⡿⠀⠀⠸⣿⣿⡟⠀⠀⣸⣿⡟⠀⣾⣿⡇⠀⣾⣿⡇⠀⣼⣿⡇",
I chatted with @kabinspace and we like how bright and contrasted the current look is. It's a bit lighter which makes it harder to read. Could you try making the font a bit more bold? If it's not as contrasted we might stick with the current Ascii art and leave it a bit simpler. Thanks for investigating this though!

2022-07-31 12:20 UTC, kabinspace commented
@osamuaoki I would like to stick with the old logo, for now, the old one seems to be more clean and bold, Thank you for your ideas nonetheless.

2022-07-31 12:21 UTC, closed without merging