Minor fix to Comment.nvim pre_hook
AstroNvim/AstroNvim pull request #888
Opened 2022-08-13 21:21 UTC by nguyenston

Minor correction to the Comment.nvim pre_hook function. As discussed in numToStr/Comment.nvim#201, `utils.ctype` attributes got renamed.

2022-08-13 21:45 UTC, mehalter requested changes
Thank you for the contribution! Could you please reword your commit message to follow Conventional Commit. If you have questions about this there are details in the Contribution Guidelines on the repo

2022-08-13 22:23 UTC, nguyenston commented
I have reworded the commit.

2022-08-14 17:38 UTC, mehalter commented
@nguyenston I'll be able to test this and make sure it's good to go tomorrow :)

2022-08-15 19:02 UTC, mehalter approved these changes
LGTM

2022-08-15 19:03 UTC, merged